language: java

jdk:
    - oraclejdk8
    - oraclejdk7

#notifications:
#    email:
#        - skylot@gmail.com

script:
    - ./gradlew clean build dist

after_success:
    - ./gradlew jacocoTestReport
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
